#!/usr/bin/env python
# coding: utf-8


ID_COV = ['Subject', 'Gender', 'Age', 'FS_IntraCranial_Vol']

FS = ['FS_L_Bankssts_Thck',
    'FS_L_Caudalanteriorcingulate_Thck',
    'FS_L_Caudalmiddlefrontal_Thck',
    'FS_L_Cuneus_Thck',
    'FS_L_Entorhinal_Thck',
    'FS_L_Fusiform_Thck',
    'FS_L_Inferiorparietal_Thck',
    'FS_L_Inferiortemporal_Thck',
    'FS_L_Isthmuscingulate_Thck',
    'FS_L_Lateraloccipital_Thck',
    'FS_L_Lateralorbitofrontal_Thck',
    'FS_L_Lingual_Thck',
    'FS_L_Medialorbitofrontal_Thck',
    'FS_L_Middletemporal_Thck',
    'FS_L_Parahippocampal_Thck',
    'FS_L_Paracentral_Thck',
    'FS_L_Parsopercularis_Thck',
    'FS_L_Parsorbitalis_Thck',
    'FS_L_Parstriangularis_Thck',
    'FS_L_Pericalcarine_Thck',
    'FS_L_Postcentral_Thck',
    'FS_L_Posteriorcingulate_Thck',
    'FS_L_Precentral_Thck',
    'FS_L_Precuneus_Thck',
    'FS_L_Rostralanteriorcingulate_Thck',
    'FS_L_Rostralmiddlefrontal_Thck',
    'FS_L_Superiorfrontal_Thck',
    'FS_L_Superiorparietal_Thck',
    'FS_L_Superiortemporal_Thck',
    'FS_L_Supramarginal_Thck',
    'FS_L_Frontalpole_Thck',
    'FS_L_Temporalpole_Thck',
    'FS_L_Transversetemporal_Thck',
    'FS_L_Insula_Thck',
    'FS_R_Bankssts_Thck',
    'FS_R_Caudalanteriorcingulate_Thck',
    'FS_R_Caudalmiddlefrontal_Thck',
    'FS_R_Cuneus_Thck',
    'FS_R_Entorhinal_Thck',
    'FS_R_Fusiform_Thck',
    'FS_R_Inferiorparietal_Thck',
    'FS_R_Inferiortemporal_Thck',
    'FS_R_Isthmuscingulate_Thck',
    'FS_R_Lateraloccipital_Thck',
    'FS_R_Lateralorbitofrontal_Thck',
    'FS_R_Lingual_Thck',
    'FS_R_Medialorbitofrontal_Thck',
    'FS_R_Middletemporal_Thck',
    'FS_R_Parahippocampal_Thck',
    'FS_R_Paracentral_Thck',
    'FS_R_Parsopercularis_Thck',
    'FS_R_Parsorbitalis_Thck',
    'FS_R_Parstriangularis_Thck',
    'FS_R_Pericalcarine_Thck',
    'FS_R_Postcentral_Thck',
    'FS_R_Posteriorcingulate_Thck',
    'FS_R_Precentral_Thck',
    'FS_R_Precuneus_Thck',
    'FS_R_Rostralanteriorcingulate_Thck',
    'FS_R_Rostralmiddlefrontal_Thck',
    'FS_R_Superiorfrontal_Thck',
    'FS_R_Superiorparietal_Thck',
    'FS_R_Superiortemporal_Thck',
    'FS_R_Supramarginal_Thck',
    'FS_R_Frontalpole_Thck',
    'FS_R_Temporalpole_Thck',
    'FS_R_Transversetemporal_Thck',
    'FS_R_Insula_Thck']


COG = ['PicSeq_AgeAdj', 
       'CardSort_AgeAdj',
       'Flanker_AgeAdj',
       'PMAT24_A_CR',
       'ReadEng_AgeAdj',
       'PicVocab_AgeAdj',
       'ProcSpeed_AgeAdj',
       'DDisc_AUC_40K',
       'IWRD_TOT',
       'ListSort_AgeAdj',
       'ER40_CR']

VOLS = ['FS_CC_Posterior_Vol','FS_CC_MidPosterior_Vol','FS_CC_Central_Vol','FS_CC_MidAnterior_Vol','FS_CC_Anterior_Vol',
       'FS_L_LatVent_Vol','FS_L_InfLatVent_Vol','FS_L_Cerebellum_WM_Vol','FS_L_Cerebellum_Cort_Vol','FS_L_ThalamusProper_Vol',
        'FS_L_Caudate_Vol','FS_L_Putamen_Vol','FS_L_Pallidum_Vol','FS_3rdVent_Vol','FS_4thVent_Vol',
        'FS_L_Hippo_Vol','FS_L_Amygdala_Vol','FS_L_AccumbensArea_Vol','FS_L_VentDC_Vol',
        'FS_R_LatVent_Vol','FS_R_InfLatVent_Vol','FS_R_Cerebellum_WM_Vol','FS_R_Cerebellum_Cort_Vol','FS_R_ThalamusProper_Vol','FS_R_Caudate_Vol',
        'FS_R_Putamen_Vol','FS_R_Pallidum_Vol','FS_R_Hippo_Vol','FS_R_Amygdala_Vol','FS_R_AccumbensArea_Vol']
